name: ci

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CTEST_PARALLEL_LEVEL: 0
  CTEST_NO_TESTS_ACTION: error
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
    - "**.py"
    - .github/workflows/ci.yml

jobs:

  unix:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]
        python-version: ["3.9", "3.13"]

    env:
      FC: gfortran-14

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[tests,lint]

    - run: flake8
    - run: mypy

    - run: pytest


  msys2:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/ucrt64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v4

    - run: pip install .[tests,lint]

    - run: pytest
